# Generated by Django 4.2.4 on 2023-09-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent_category",
        ),
    ]
