# Generated by Django 4.2.4 on 2023-09-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_remove_category_parent_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="profile",
        ),
    ]
