# Generated by Django 4.2.4 on 2023-09-05 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_remove_category_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
