# Generated by Django 4.1 on 2024-03-11 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_income_family_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="family_member",
        ),
    ]
