# Generated by Django 4.1 on 2024-03-11 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_remove_income_family_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="family_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
