# Generated by Django 4.2.4 on 2023-09-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
