# Generated by Django 4.1 on 2024-03-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0005_income_family_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="type",
            field=models.CharField(
                choices=[
                    ("kid", "Kid"),
                    ("parent", "Parent"),
                    ("grandparent", "Grandparent"),
                ],
                default="Parent",
                max_length=32,
            ),
        ),
    ]
