# Generated by Django 4.1 on 2024-03-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_familymember_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="type",
            field=models.CharField(
                choices=[
                    ("Kid", "Kid"),
                    ("Parent", "Parent"),
                    ("Grandparent", "Grandparent"),
                ],
                default="Parent",
                max_length=32,
            ),
        ),
    ]
